# Generated by Django 5.1.2 on 2024-12-18 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrestriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestriction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrestriction',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
