# Generated by Django 5.1.2 on 2024-11-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Monstruo grande', 'Monstruo grande'), ('Monstruo pequeño', 'Monstruo pequeño'), ('Flora', 'Flora')], max_length=20)),
                ('descripcion', models.TextField()),
                ('resumen', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
