# Generated by Django 5.1.2 on 2024-11-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradablog',
            name='tipo',
            field=models.CharField(choices=[('Monstruo grande', 'Monstruo grande'), ('Monstruo chico', 'Monstruo chico'), ('Flora', 'Flora')], max_length=20),
        ),
    ]
