# Generated by Django 5.1.2 on 2024-12-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradablog',
            name='tipo',
            field=models.CharField(choices=[('small_monster', 'Monstruo Pequeño'), ('large_monster', 'Monstruo Grande'), ('elder_dragon', 'Dragón Anciano')], max_length=20),
        ),
    ]
