# Generated by Django 5.1.2 on 2024-12-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entradablog_monster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradablog',
            name='habitat',
        ),
        migrations.DeleteModel(
            name='Habitat',
        ),
    ]
