# Generated by Django 5.1.2 on 2024-12-05 05:29

import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_entradablog_habitat_delete_habitat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradablog',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AddField(
            model_name='entradablog',
            name='imagen_recortada',
            field=image_cropping.fields.ImageRatioField('imagen', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen recortada'),
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='monster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='blog.monster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradablog',
            name='resumen',
            field=models.TextField(help_text='Breve descripción que aparecerá en las listas'),
        ),
    ]
