# Generated by Django 5.1.2 on 2024-12-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_entradablog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'verbose_name': 'Monstruo', 'verbose_name_plural': 'Monstruos'},
        ),
        migrations.RemoveField(
            model_name='entradablog',
            name='imagen_recortada',
        ),
    ]
